### ISSUE TITLE
Provide Example Deploying Smart Contract

### ISSUE THREAD

**Issue by rlkelly** [maht0rz/tezos-environment-manager#15]
It would be helpful if you provided a basic example of deploying and interacting with a smart contract using granary.

**Comment by maht0rz** [comment]
Hi @rlkelly, you can find an updated example with origination (deployment) and invocation for a smart contract in [Granary's starter kit](https://github.com/stove-labs/granary-starter-kit).

If this is sufficient please close the issue, thanks!
